  Killing any running python_d.exe instances...
  "C:\cpython-3.11.1\PCbuild\\..\externals\pythonx86\tools\python.exe"
  Using PythonForBuild="C:\cpython-3.11.1\PCbuild\\..\externals\pythonx86\tools\python.exe"
  Generated sources are up to date
  Getting build info from git
  fatal: not a git repository (or any of the parent directories): .git
C:\cpython-3.11.1\PCbuild\pythoncore.vcxproj(579,5): warning MSB3073: El comando "git name-rev --name-only HEAD > "C:\cpython-3.11.1\PCbuild\obj\311amd64_Debug\pythoncore\gitbranch.txt"" salió con el código 128.
  fatal: not a git repository (or any of the parent directories): .git
C:\cpython-3.11.1\PCbuild\pythoncore.vcxproj(580,5): warning MSB3073: El comando "git rev-parse --short HEAD > "C:\cpython-3.11.1\PCbuild\obj\311amd64_Debug\pythoncore\gitversion.txt"" salió con el código 128.
  fatal: not a git repository (or any of the parent directories): .git
C:\cpython-3.11.1\PCbuild\pythoncore.vcxproj(581,5): warning MSB3073: El comando "git describe --all --always --dirty > "C:\cpython-3.11.1\PCbuild\obj\311amd64_Debug\pythoncore\gittag.txt"" salió con el código 128.
  Building : 
  getpath.c
  _abc.c
  _bisectmodule.c
  blake2module.c
  blake2b_impl.c
  blake2s_impl.c
  _codecsmodule.c
  _collectionsmodule.c
  _contextvarsmodule.c
  _csv.c
  _functoolsmodule.c
  _heapqmodule.c
  _json.c
  _localemodule.c
  _lsprof.c
  _pickle.c
  _randommodule.c
  sha3module.c
  sre.c
  _stat.c
  _struct.c
  _weakref.c
  arraymodule.c
  atexitmodule.c
  audioop.c
  cmathmodule.c
  _datetimemodule.c
  errnomodule.c
  faulthandler.c
  gcmodule.c
  itertoolsmodule.c
  main.c
  mathmodule.c
  md5module.c
  mmapmodule.c
  _opcode.c
  _operator.c
  posixmodule.c
  rotatingtree.c
  sha1module.c
  sha256module.c
  sha512module.c
  signalmodule.c
  _statisticsmodule.c
  symtablemodule.c
  _threadmodule.c
  _tracemalloc.c
  _typingmodule.c
  timemodule.c
  xxsubtype.c
  _xxsubinterpretersmodule.c
  fileio.c
  bytesio.c
  stringio.c
  bufferedio.c
  iobase.c
  textio.c
  winconsoleio.c
  _iomodule.c
  _codecs_cn.c
  _codecs_hk.c
  _codecs_iso2022.c
  _codecs_jp.c
  _codecs_kr.c
  _codecs_tw.c
  multibytecodec.c
  _winapi.c
  abstract.c
  accu.c
  boolobject.c
  bytearrayobject.c
  bytes_methods.c
  bytesobject.c
  call.c
  capsule.c
  cellobject.c
  classobject.c
  codeobject.c
  complexobject.c
  descrobject.c
  dictobject.c
  enumobject.c
  exceptions.c
  fileobject.c
  floatobject.c
  frameobject.c
  funcobject.c
  genericaliasobject.c
  genobject.c
  interpreteridobject.c
  iterobject.c
  listobject.c
  longobject.c
  memoryobject.c
  methodobject.c
  moduleobject.c
  namespaceobject.c
  object.c
  obmalloc.c
  odictobject.c
  picklebufobject.c
  rangeobject.c
  setobject.c
  sliceobject.c
  structseq.c
  tupleobject.c
  typeobject.c
  unicodectype.c
  unicodeobject.c
  unionobject.c
  weakrefobject.c
  myreadline.c
  tokenizer.c
  token.c
  pegen.c
  pegen_errors.c
  action_helpers.c
  parser.c
  string_parser.c
  peg_api.c
  invalid_parameter_handler.c
  winreg.c
  config.c
  msvcrtmodule.c
  pyhash.c
  _warnings.c
  asdl.c
  ast.c
  ast_opt.c
  ast_unparse.c
  bltinmodule.c
  bootstrap_hash.c
  ceval.c
  codecs.c
  compile.c
  context.c
  dynamic_annotations.c
  dynload_win.c
  errors.c
  fileutils.c
  formatter_unicode.c
  frame.c
  frozen.c
  future.c
  getargs.c
  getcompiler.c
  getcopyright.c
  getopt.c
  getplatform.c
  getversion.c
  hamt.c
  hashtable.c
  import.c
  importdl.c
  initconfig.c
  marshal.c
  modsupport.c
  mysnprintf.c
  mystrtoul.c
  pathconfig.c
  preconfig.c
  pyarena.c
  pyctype.c
  pyfpe.c
  pylifecycle.c
  pymath.c
  pytime.c
  pystate.c
  pystrcmp.c
  pystrhex.c
  pystrtod.c
  dtoa.c
  Python-ast.c
  Python-tokenize.c
  pythonrun.c
  specialize.c
  suggestions.c
  structmember.c
  symtable.c
  thread.c
  traceback.c
  deepfreeze.c
  zlibmodule.c
  adler32.c
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\adler32.c)
  compress.c
  crc32.c
  infback.c
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\crc32.c)
  inffast.c
  inflate.c
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\infback.c)
  inftrees.c
  trees.c
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\inffast.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen ..\Modules\zlibmodule.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\compress.c)
  uncompr.c
  zutil.c
  dl_nt.c
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\trees.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\inflate.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\inftrees.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\uncompr.c)
C:\cpython-3.11.1\externals\zlib-1.2.13\zconf.h(488,14): fatal  error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file or directory (compilando archivo de origen C:\cpython-3.11.1\externals\zlib-1.2.13\zutil.c)
